In [2]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

# 1. Работа с массивами NumPy

**N. Все упражнения ниже нужно делать без использования циклов Python**

**1.** Cоздать вектор

$$(2, \frac{2^2}{2}, \ldots, \frac{2^{20}}{20})$$

Можно использовать функции [np.arange()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html), [np.ones()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html)

In [ ]:
a = ((2*np.ones(20))**np.arange(1, 21))/np.arange(1, 21)
a

array([2.00000000e+00, 2.00000000e+00, 2.66666667e+00, 4.00000000e+00,
       6.40000000e+00, 1.06666667e+01, 1.82857143e+01, 3.20000000e+01,
       5.68888889e+01, 1.02400000e+02, 1.86181818e+02, 3.41333333e+02,
       6.30153846e+02, 1.17028571e+03, 2.18453333e+03, 4.09600000e+03,
       7.71011765e+03, 1.45635556e+04, 2.75941053e+04, 5.24288000e+04])

**2.** Посчитать:

$$\sum\limits_{i=0}^{5}{0.1^{3i}0.2^{4i}}$$


In [ ]:
b = ((0.1**(3*np.arange(6)))*(0.2**(4*np.arange(6)))).sum()
b

1.00000160000256

**3.** Создать нулевую матрицe $8 \times 8$, и заполнить её единицами в шахматном порядке.

In [32]:
def gen(i, j):
  return np.where((i+j)%2 == 0, 1, 0)

b = np.fromfunction(gen, (8, 8), dtype=int)
b

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

**4.** Есть 5 точек в декартовой системе координат (в виде матрицы $X$ размерностью $5 \times 2$), сконвертируйте эти точки в полярную систему координат.

In [ ]:
X = np.random.random((5, 2))

r = np.sqrt(X[:, 0]**2 + X[:, 1]**2)
f = np.arccos(X[:, 0]/r)
Y = np.vstack((r, f)).T
Y

array([[0.7836729 , 0.48792126],
       [0.63079921, 1.48461866],
       [1.07770818, 0.51551745],
       [0.87132413, 0.27906982],
       [0.89910522, 0.3979349 ]])

**5.** Найдите индексы максимального элемента в случайной матрице $10 \times 10$.

Cм. [np.argmax()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html).

In [ ]:
X = np.random.random((10, 10))

ind = np.argmax(X)
d = (ind//10, ind - (ind//10)*10)
d

(7, 6)

**6.** Есть 10 точек ($X$) и ещё одна ($y$). Найти в $X$ ближайшую к $y$ точку.

In [ ]:
X = np.random.random((10, 2))
y = np.random.random((1, 2))
e = np.argmax(((X - y)**2).sum(axis=1))
X[e]

array([0.01265813, 0.20349296])

**7.** Дана функция:

$$
 \begin{cases}
    x^2 + 2x + 6, & x < 0  \\
    x + 6, & 0 \le x \le 2 \\
    x^2 + 4x - 4, & x \ge 2
 \end{cases}
$$

Постройте массив из её значений на  $-3 \le x \le 3$.

In [ ]:
x1, x2, x3 = np.arange(-3, 0, 0.2), np.arange(0, 2.1, 0.2), np.arange(2, 0, 3.1)
f = np.hstack(((x1**2 + 2*x1) + 6, x2 + 6, x3**2 + 4*x3 -4))
f

array([9.  , 8.24, 7.56, 6.96, 6.44, 6.  , 5.64, 5.36, 5.16, 5.04, 5.  ,
       5.04, 5.16, 5.36, 5.64, 6.  , 6.2 , 6.4 , 6.6 , 6.8 , 7.  , 7.2 ,
       7.4 , 7.6 , 7.8 , 8.  ])

**8.** Из каждого элемента матрицы вычесть среднее арифметическое от всех элементов в соответствующей строке (после чего среднее значение каждой строки должно равняться нулю).

Cм. [np.mean()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html).

In [ ]:
X = np.random.random((10, 10))

X = X - X.mean(axis=1).reshape(10, 1)
X.mean(axis=1)

array([-4.44089210e-17, -3.33066907e-17,  5.55111512e-18, -3.33066907e-17,
       -5.55111512e-17,  2.22044605e-17,  1.33226763e-16,  0.00000000e+00,
       -8.88178420e-17,  0.00000000e+00])

**9.** Есть массив из 1000 чисел, полученных из генератора случайных чисел, имеющий нормальное распределение. Посчитайте выборочное среднее и выборочную дисперсию. 

In [ ]:
X = np.random.normal(loc=5, scale=2., size=1000)

m = X.sum()/len(X)
d = ((X - m)**2).sum() / len(X)
print(f"mean = {m}, disp = {d}")

mean = 4.985546628747563, disp = 3.836622872274078


**10.** Создать матрицу:

$$
\begin{pmatrix}
0 & 1 & 2 & 3 & 4 \\
1 & 2 & 3 & 4 & 0 \\
2 & 3 & 4 & 0 & 1 \\
3 & 4 & 0 & 1 & 2 \\
4 & 0 & 1 & 2 & 3
\end{pmatrix}
$$

In [33]:
def gen(i, j):
  return np.where((i+j-5) >= 0, i + j - 5, i + j)

z = np.fromfunction(gen, (5, 5), dtype=int)
z

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 0],
       [2, 3, 4, 0, 1],
       [3, 4, 0, 1, 2],
       [4, 0, 1, 2, 3]])

**11.** Есть следующий алгоритм семплинирования, на вход функции подается вектор из целых положительных чисел и число семплов.

In [42]:
def sample(x, c):
    assert len(x) > 0
    
    s = np.sum(x)
    res = []
    for _ in range(c):
        val = s * np.random.random()
        print(val)
        cur, idx = 0, 0        
        while cur + x[idx] <= val:
            cur += x[idx]
            idx += 1
            
        res.append(idx)
    return res

            
sample([50, 3, 1, 7, 20], 5)    

66.04622155533677
63.85772342212051
71.47846185618539
57.47796737772245
3.060632906294311


[4, 4, 4, 3, 0]

Реализуйте данный алгоритм более оптимальным способом, без использования циклов.

In [47]:
def optim_sample(x, c):
    assert len(x) > 0
    
    s = np.sum(x)
    val = s*np.random.random(c).reshape((c, 1))
    x = np.array(x).cumsum().reshape((1, c))
    res = (x < val).astype('int')
    return res.sum(axis=1)

optim_sample([50, 3, 1, 7, 20], 5)

array([4, 0, 4, 0, 4])